export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export type ADD_ITEM_REQUEST = typeof ADD_ITEM_REQUEST;
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export type ADD_ITEM_SUCCESS = typeof ADD_ITEM_SUCCESS;
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';
export type ADD_ITEM_FAILURE = typeof ADD_ITEM_FAILURE;

export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST';
export type REMOVE_ITEM_REQUEST = typeof REMOVE_ITEM_REQUEST;
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export type REMOVE_ITEM_SUCCESS = typeof REMOVE_ITEM_SUCCESS;
export const REMOVE_ITEM_FAILURE = 'REMOVE_ITEM_FAILURE';
export type REMOVE_ITEM_FAILURE = typeof REMOVE_ITEM_FAILURE;

export const AUTH_REQUEST = 'AUTH_REQUEST';
export type AUTH_REQUEST = typeof AUTH_REQUEST;
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export type AUTH_SUCCESS = typeof AUTH_SUCCESS;
export const AUTH_FAILURE = 'AUTH_FAILURE';
export type AUTH_FAILURE = typeof AUTH_FAILURE;

export const FETCH_REQUEST = 'FETCH_REQUEST';
export type FETCH_REQUEST = typeof FETCH_REQUEST;
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export type FETCH_SUCCESS = typeof FETCH_SUCCESS;
export const FETCH_FAILURE = 'FETCH_FAILURE';
export type FETCH_FAILURE = typeof FETCH_FAILURE;
